name: demo-stream
environments:
  prod:
    - environment-prod.yml
  dev:
    - environment-dev.yml
    - environment-prod.yml
commands:
  test:
    cmd: pytest
    environment: dev
    variables:
      # This allows importing directly from the project root
      PYTHONPATH: .
