name: prod
channels:
  - conda-forge
dependencies:
  # renovate: datasource=conda depName=conda-forge/python
  - python=3.12.4
  # renovate: datasource=conda depName=conda-forge/pip
  - pip=25.0.1
  # renovate: datasource=conda depName=conda-forge/fastapi
  - fastapi=0.115.12
variables:
prefix:
platforms:
  - osx-arm64
  - linux-64
