name: prod
channels:
  - conda-forge
dependencies:
  # renovate: datasource=conda depName=conda-forge/python
  - python=3.12.6
  # renovate: datasource=conda depName=conda-forge/pip
  - pip=24.2
  # renovate: datasource=conda depName=conda-forge/fastapi
  - fastapi=0.112.0
variables:
prefix:
platforms:
  - osx-arm64
  - linux-64
