[tool.mypy]
disallow_untyped_defs = true
files = [
  "main.py",
  "tests/**/*.py"
]
python_version = "3.12"

[tool.pytest.ini_options]
addopts = []
asyncio_mode = "auto"
norecursedirs = ["envs"]

[tool.ruff]
line-length = 99
target-version = "py39"

[tool.ruff.lint]
# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
# see https://docs.astral.sh/ruff/rules/
select = ["F", "E", "W", "C90", "I", "UP"]
